/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsPhishingRouteImport } from './routes/tools.phishing'
import { Route as ToolsPasswordRouteImport } from './routes/tools.password'
import { Route as ToolsMalwareRouteImport } from './routes/tools.malware'
import { Route as ToolsEncryptRouteImport } from './routes/tools.encrypt'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPhishingRoute = ToolsPhishingRouteImport.update({
  id: '/tools/phishing',
  path: '/tools/phishing',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordRoute = ToolsPasswordRouteImport.update({
  id: '/tools/password',
  path: '/tools/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMalwareRoute = ToolsMalwareRouteImport.update({
  id: '/tools/malware',
  path: '/tools/malware',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEncryptRoute = ToolsEncryptRouteImport.update({
  id: '/tools/encrypt',
  path: '/tools/encrypt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/tools/encrypt': typeof ToolsEncryptRoute
  '/tools/malware': typeof ToolsMalwareRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/phishing': typeof ToolsPhishingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/tools/encrypt': typeof ToolsEncryptRoute
  '/tools/malware': typeof ToolsMalwareRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/phishing': typeof ToolsPhishingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/tools/encrypt': typeof ToolsEncryptRoute
  '/tools/malware': typeof ToolsMalwareRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/phishing': typeof ToolsPhishingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/tools/encrypt'
    | '/tools/malware'
    | '/tools/password'
    | '/tools/phishing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/tools/encrypt'
    | '/tools/malware'
    | '/tools/password'
    | '/tools/phishing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/tools/encrypt'
    | '/tools/malware'
    | '/tools/password'
    | '/tools/phishing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ToolsEncryptRoute: typeof ToolsEncryptRoute
  ToolsMalwareRoute: typeof ToolsMalwareRoute
  ToolsPasswordRoute: typeof ToolsPasswordRoute
  ToolsPhishingRoute: typeof ToolsPhishingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/phishing': {
      id: '/tools/phishing'
      path: '/tools/phishing'
      fullPath: '/tools/phishing'
      preLoaderRoute: typeof ToolsPhishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password': {
      id: '/tools/password'
      path: '/tools/password'
      fullPath: '/tools/password'
      preLoaderRoute: typeof ToolsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/malware': {
      id: '/tools/malware'
      path: '/tools/malware'
      fullPath: '/tools/malware'
      preLoaderRoute: typeof ToolsMalwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/encrypt': {
      id: '/tools/encrypt'
      path: '/tools/encrypt'
      fullPath: '/tools/encrypt'
      preLoaderRoute: typeof ToolsEncryptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ToolsEncryptRoute: ToolsEncryptRoute,
  ToolsMalwareRoute: ToolsMalwareRoute,
  ToolsPasswordRoute: ToolsPasswordRoute,
  ToolsPhishingRoute: ToolsPhishingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
